
OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true

    Specs:
      - Hostname: orderer
        SANS:
            - "localhost"
            - "127.0.0.1"
      - Hostname: orderer2
        SANS:
          - "localhost"
          - "127.0.0.1"
      - Hostname: orderer3
        SANS:
            - "localhost"
            - "127.0.0.1"

PeerOrgs:
  - Name: FarmersAssociation
    Domain: farmersAssociation.example.com
    EnableNodeOUs: true

    Template:
      Count: 2
      SANS:
        - "localhost"

    Users:
      Count: 1

  - Name: WholesalersAssociation
    Domain: wholesalersAssociation.example.com
    EnableNodeOUs: true

    Template:
      Count: 2
      SANS:
        - "localhost"

    Users:
      Count: 1

  - Name: RetailersAssociation
    Domain: retailersAssociation.example.com
    EnableNodeOUs: true

    Template:
      Count: 2
      SANS:
        - "localhost"

    Users:
      Count: 1