---
name: first-network-seedsAssociation
version: 1.0.0
channel:
  mychannel:
    orderers:
    - ordererexample.com
    - orderer2.example.com
    - orderer3.example.com
    peers:
      peer0.seedsAssociation.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      #
      peer1.seedsAssociation.example.com:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
       #
      peer0.farmersAssociation.example.com:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      #
      peer1.farmersAssociation.example.com:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      #
      peer0.merchantsAssociation.example.com:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      #
      peer1.merchantsAssociation.example.com:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

organizations:
  SeedsAssociation:
    mspid: SeedsAssociationMSP
    peers:
    - peer0.seedsAssociation.example.com
    - peer1.seedsAssociation.example.com
    certificateAuthorities:
    - ca.seedsAssociation.example.com
  FarmersAssociation:
    mspid: FarmersAssociationMSP
    peers:
    - peer0.farmersAssociation.example.com
    - peer1.farmersAssociation.example.com
    certificateAuthorities:
    - ca.farmersAssociation.example.com
  MerchantsAssociation:
    mspid: MerchantsAssociationMSP
    peers:
    - peer0.merchantsAssociation.example.com
    - peer1.merchantsAssociation.example.com
    certificateAuthorities:
    - ca.merchantsAssociation.example.com
  

orderers:
  orderer.example.com:
    url: grpc://104.46.113.219:7050
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICFjCCAb2gAwIBAgIUBflk+1YccwJQERxiuUEKS5mdl9cwCgYIKoZIzj0EAwIw
        aDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQK
        EwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMt
        Y2Etc2VydmVyMB4XDTIwMTIyNjA2MDYwMFoXDTM1MTIyMzA2MDYwMFowaDELMAkG
        A1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQKEwtIeXBl
        cmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMtY2Etc2Vy
        dmVyMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEWe4HYnx3XiNTvaCtwepGA52C
        6TsfysTM4eDE1OC7dcGw/jEdwGyCr72odZs5GZF1hppMsMLn9XSAY8U+1ooNq6NF
        MEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYE
        FFSJDZq6+sylBZb4tDmGYbq7s3gLMAoGCCqGSM49BAMCA0cAMEQCIGAP0fb0e0Jp
        di2GZKdJ9GKAThRiUuc2As8hLgN+A7teAiBtwBUqYbqdjVTJCUEG+TgkUljRYd9o
        GDTVfY8RZF6d5A==
        -----END CERTIFICATE-----
    grpcOptions:
      ssl-target-name-override: orderer.example.com

  orderer2.example.com:
    url: grpc://104.46.113.219:8050
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICFjCCAb2gAwIBAgIUBflk+1YccwJQERxiuUEKS5mdl9cwCgYIKoZIzj0EAwIw
        aDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQK
        EwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMt
        Y2Etc2VydmVyMB4XDTIwMTIyNjA2MDYwMFoXDTM1MTIyMzA2MDYwMFowaDELMAkG
        A1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQKEwtIeXBl
        cmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMtY2Etc2Vy
        dmVyMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEWe4HYnx3XiNTvaCtwepGA52C
        6TsfysTM4eDE1OC7dcGw/jEdwGyCr72odZs5GZF1hppMsMLn9XSAY8U+1ooNq6NF
        MEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYE
        FFSJDZq6+sylBZb4tDmGYbq7s3gLMAoGCCqGSM49BAMCA0cAMEQCIGAP0fb0e0Jp
        di2GZKdJ9GKAThRiUuc2As8hLgN+A7teAiBtwBUqYbqdjVTJCUEG+TgkUljRYd9o
        GDTVfY8RZF6d5A==
        -----END CERTIFICATE-----
    grpcOptions:
      ssl-target-name-override: orderer2.example.com

  orderer3.example.com:
    url: grpc://104.46.113.219:9050
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICFjCCAb2gAwIBAgIUBflk+1YccwJQERxiuUEKS5mdl9cwCgYIKoZIzj0EAwIw
        aDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQK
        EwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMt
        Y2Etc2VydmVyMB4XDTIwMTIyNjA2MDYwMFoXDTM1MTIyMzA2MDYwMFowaDELMAkG
        A1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQKEwtIeXBl
        cmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMtY2Etc2Vy
        dmVyMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEWe4HYnx3XiNTvaCtwepGA52C
        6TsfysTM4eDE1OC7dcGw/jEdwGyCr72odZs5GZF1hppMsMLn9XSAY8U+1ooNq6NF
        MEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYE
        FFSJDZq6+sylBZb4tDmGYbq7s3gLMAoGCCqGSM49BAMCA0cAMEQCIGAP0fb0e0Jp
        di2GZKdJ9GKAThRiUuc2As8hLgN+A7teAiBtwBUqYbqdjVTJCUEG+TgkUljRYd9o
        GDTVfY8RZF6d5A==
        -----END CERTIFICATE-----
    grpcOptions:
      ssl-target-name-override: orderer.example.com


peers:
  peer0.seedsAssociation.example.com:
    url: grpcs://168.62.175.188:7051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICFzCCAb2gAwIBAgIUBc7C7vXl/eelTZLwiFd2Cx3PlRYwCgYIKoZIzj0EAwIw
        aDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQK
        EwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMt
        Y2Etc2VydmVyMB4XDTIwMTIyNTEyNDEwMFoXDTM1MTIyMjEyNDEwMFowaDELMAkG
        A1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQKEwtIeXBl
        cmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMtY2Etc2Vy
        dmVyMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEcACRWi7uU4Ej0KyhdcRnBsE/
        aSPyO2MQ+WplPaUd2we8NlUqeMGR7y4uCyk7jCFNgZdp15Z6LL+VTfmkLHBs1qNF
        MEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYE
        FMQ3czhzAEXH+s9Y2EMSv4kUBjpEMAoGCCqGSM49BAMCA0gAMEUCIQD7uboKXvW1
        ++h5PBmBZrrQMpX+CGS8rNEXscXmiHOrbwIgbLn9Maq1yYGrMIQJiJkScM0U3d68
        9wLybdfmDOAG30Q=
        -----END CERTIFICATE-----
        
    grpcOptions:
      ssl-target-name-override: peer0.seedsAssociation.example.com
      hostnameOverride: peer0.seedsAssociation.example.com

  peer1.seedsAssociation.example.com:
    url: grpcs://168.62.175.188:8051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICFzCCAb2gAwIBAgIUBc7C7vXl/eelTZLwiFd2Cx3PlRYwCgYIKoZIzj0EAwIw
        aDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQK
        EwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMt
        Y2Etc2VydmVyMB4XDTIwMTIyNTEyNDEwMFoXDTM1MTIyMjEyNDEwMFowaDELMAkG
        A1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQKEwtIeXBl
        cmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMtY2Etc2Vy
        dmVyMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEcACRWi7uU4Ej0KyhdcRnBsE/
        aSPyO2MQ+WplPaUd2we8NlUqeMGR7y4uCyk7jCFNgZdp15Z6LL+VTfmkLHBs1qNF
        MEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYE
        FMQ3czhzAEXH+s9Y2EMSv4kUBjpEMAoGCCqGSM49BAMCA0gAMEUCIQD7uboKXvW1
        ++h5PBmBZrrQMpX+CGS8rNEXscXmiHOrbwIgbLn9Maq1yYGrMIQJiJkScM0U3d68
        9wLybdfmDOAG30Q=
        -----END CERTIFICATE-----
        
    grpcOptions:
      ssl-target-name-override: peer1.seedsAssociation.example.com
      hostnameOverride: peer1.seedsAssociation.example.com
  
  peer0.farmersAssociation.example.com:
    url: grpcs://52.170.250.32:9051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICFjCCAb2gAwIBAgIULuD1UOk0GMtVb4Tcu5LYKgtP7K4wCgYIKoZIzj0EAwIw
        aDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQK
        EwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMt
        Y2Etc2VydmVyMB4XDTIwMTIyNjA2MDYwMFoXDTM1MTIyMzA2MDYwMFowaDELMAkG
        A1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQKEwtIeXBl
        cmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMtY2Etc2Vy
        dmVyMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEoQ+p7hz6TdGMUjHIsHmU4KQR
        QhC8OlvWwHZDxnz4wo2sM5ecHCL3NPStAtdoWDpuqEgAo7o5xlPA6xO+dxte4KNF
        MEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYE
        FP2nAXwMyjmP3B3NQ2RV9MDW+X56MAoGCCqGSM49BAMCA0cAMEQCIAvpJC3gS82L
        4EWeLgDU15qBm+KWYo66Z9BAx36e1FxXAiBIt8W+JzQDuOEpXKFrlsWdujkeD8Hl
        sRNscT/AKhOzSQ==
        -----END CERTIFICATE-----
        
    grpcOptions:
      ssl-target-name-override: peer0.farmersAssociation.example.com
      hostnameOverride: peer0.farmersAssociation.example.com

  peer1.farmersAssociation.example.com:
    url: grpcs://52.170.250.32:10051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICFjCCAb2gAwIBAgIULuD1UOk0GMtVb4Tcu5LYKgtP7K4wCgYIKoZIzj0EAwIw
        aDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQK
        EwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMt
        Y2Etc2VydmVyMB4XDTIwMTIyNjA2MDYwMFoXDTM1MTIyMzA2MDYwMFowaDELMAkG
        A1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQKEwtIeXBl
        cmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMtY2Etc2Vy
        dmVyMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEoQ+p7hz6TdGMUjHIsHmU4KQR
        QhC8OlvWwHZDxnz4wo2sM5ecHCL3NPStAtdoWDpuqEgAo7o5xlPA6xO+dxte4KNF
        MEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYE
        FP2nAXwMyjmP3B3NQ2RV9MDW+X56MAoGCCqGSM49BAMCA0cAMEQCIAvpJC3gS82L
        4EWeLgDU15qBm+KWYo66Z9BAx36e1FxXAiBIt8W+JzQDuOEpXKFrlsWdujkeD8Hl
        sRNscT/AKhOzSQ==
        -----END CERTIFICATE-----
        
    grpcOptions:
      ssl-target-name-override: peer1.farmersAssociation.example.com
      hostnameOverride: peer1.farmersAssociation.example.com

  peer0.merchantsAssociation.example.com:
    url: grpcs://20.83.163.11:11051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICFzCCAb2gAwIBAgIUEWhWTNWB0B1YTxCZ0XAgWdMHY/0wCgYIKoZIzj0EAwIw
        aDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQK
        EwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMt
        Y2Etc2VydmVyMB4XDTIwMTIyNjA2MDYwMFoXDTM1MTIyMzA2MDYwMFowaDELMAkG
        A1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQKEwtIeXBl
        cmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMtY2Etc2Vy
        dmVyMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAELBBQuNl+rLCDYd2N1OdkrjoU
        cpaZMyoWD5ydI79ZGiW2hkadJF61YrOTAFnrMn3XXmvA/HocUKH99lcr13skbaNF
        MEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYE
        FMdNdca1HlzIqTdjDMYdEiTta+MvMAoGCCqGSM49BAMCA0gAMEUCIQDKZL/Fa+sQ
        VxkG/E20dJwSRllnC2wktSOGYr8vDV9hsAIgPyc2bacCYB4Tcu/W483A4QTpCdmx
        wFV7hBOe1Khqncs=
        -----END CERTIFICATE-----
        
    grpcOptions:
      ssl-target-name-override: peer0.merchantsAssociation.example.com
      hostnameOverride: peer0.merchantsAssociation.example.com

  peer1.merchantsAssociation.example.com:
    url: grpcs://20.83.163.11:12051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICFzCCAb2gAwIBAgIUEWhWTNWB0B1YTxCZ0XAgWdMHY/0wCgYIKoZIzj0EAwIw
        aDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQK
        EwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMt
        Y2Etc2VydmVyMB4XDTIwMTIyNjA2MDYwMFoXDTM1MTIyMzA2MDYwMFowaDELMAkG
        A1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQKEwtIeXBl
        cmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMtY2Etc2Vy
        dmVyMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAELBBQuNl+rLCDYd2N1OdkrjoU
        cpaZMyoWD5ydI79ZGiW2hkadJF61YrOTAFnrMn3XXmvA/HocUKH99lcr13skbaNF
        MEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYE
        FMdNdca1HlzIqTdjDMYdEiTta+MvMAoGCCqGSM49BAMCA0gAMEUCIQDKZL/Fa+sQ
        VxkG/E20dJwSRllnC2wktSOGYr8vDV9hsAIgPyc2bacCYB4Tcu/W483A4QTpCdmx
        wFV7hBOe1Khqncs=
        -----END CERTIFICATE-----
        
    grpcOptions:
      ssl-target-name-override: peer1.merchantsAssociation.example.com
      hostnameOverride: peer1.merchantsAssociation.example.com



certificateAuthorities:
  ca.seedsAssociation.example.com:
    url: https://168.62.175.188:7054
    caName: ca.seedsAssociation.example.com
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICFzCCAb2gAwIBAgIUBc7C7vXl/eelTZLwiFd2Cx3PlRYwCgYIKoZIzj0EAwIw
        aDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQK
        EwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMt
        Y2Etc2VydmVyMB4XDTIwMTIyNTEyNDEwMFoXDTM1MTIyMjEyNDEwMFowaDELMAkG
        A1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQKEwtIeXBl
        cmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMtY2Etc2Vy
        dmVyMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEcACRWi7uU4Ej0KyhdcRnBsE/
        aSPyO2MQ+WplPaUd2we8NlUqeMGR7y4uCyk7jCFNgZdp15Z6LL+VTfmkLHBs1qNF
        MEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYE
        FMQ3czhzAEXH+s9Y2EMSv4kUBjpEMAoGCCqGSM49BAMCA0gAMEUCIQD7uboKXvW1
        ++h5PBmBZrrQMpX+CGS8rNEXscXmiHOrbwIgbLn9Maq1yYGrMIQJiJkScM0U3d68
        9wLybdfmDOAG30Q=
        -----END CERTIFICATE-----
        
    httpOptions:
      verify: false
  
  ca.farmersAssociation.example.com:
    url: https://52.170.250.32:8054
    caName: ca.farmersAssociation.example.com
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----

        MIICFjCCAb2gAwIBAgIULuD1UOk0GMtVb4Tcu5LYKgtP7K4wCgYIKoZIzj0EAwIw
        aDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQK
        EwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMt
        Y2Etc2VydmVyMB4XDTIwMTIyNjA2MDYwMFoXDTM1MTIyMzA2MDYwMFowaDELMAkG
        A1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQKEwtIeXBl
        cmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMtY2Etc2Vy
        dmVyMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEoQ+p7hz6TdGMUjHIsHmU4KQR
        QhC8OlvWwHZDxnz4wo2sM5ecHCL3NPStAtdoWDpuqEgAo7o5xlPA6xO+dxte4KNF
        MEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYE
        FP2nAXwMyjmP3B3NQ2RV9MDW+X56MAoGCCqGSM49BAMCA0cAMEQCIAvpJC3gS82L
        4EWeLgDU15qBm+KWYo66Z9BAx36e1FxXAiBIt8W+JzQDuOEpXKFrlsWdujkeD8Hl
        sRNscT/AKhOzSQ==
        -----END CERTIFICATE-----
        
    httpOptions:
      verify: false

  ca.merchantsAssociation.example.com:
    url: https://20.83.163.11:8054
    caName: ca.merchantsAssociation.example.com
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICFzCCAb2gAwIBAgIUEWhWTNWB0B1YTxCZ0XAgWdMHY/0wCgYIKoZIzj0EAwIw
        aDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQK
        EwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMt
        Y2Etc2VydmVyMB4XDTIwMTIyNjA2MDYwMFoXDTM1MTIyMzA2MDYwMFowaDELMAkG
        A1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQKEwtIeXBl
        cmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMtY2Etc2Vy
        dmVyMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAELBBQuNl+rLCDYd2N1OdkrjoU
        cpaZMyoWD5ydI79ZGiW2hkadJF61YrOTAFnrMn3XXmvA/HocUKH99lcr13skbaNF
        MEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYE
        FMdNdca1HlzIqTdjDMYdEiTta+MvMAoGCCqGSM49BAMCA0gAMEUCIQDKZL/Fa+sQ
        VxkG/E20dJwSRllnC2wktSOGYr8vDV9hsAIgPyc2bacCYB4Tcu/W483A4QTpCdmx
        wFV7hBOe1Khqncs=
        -----END CERTIFICATE-----
        
    httpOptions:
      verify: false